services:
  express:
    build:
      context: ./Express-server
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://toledo:123@mongo:27017/TallerMilca?authSource=admin
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=change_this_secret_in_prod
      - PORT=4000
    volumes:
      - ./Express-server:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - postgres
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: toledo
      MONGO_INITDB_ROOT_PASSWORD: "123"
      MONGO_INITDB_DATABASE: TallerMilca
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  react:
    build:
      context: ./ReactWithForm
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ReactWithForm:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - express
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"

volumes:
  mongo-data:
  pg-data:
