services:
  express:
    build:
      context: ./Express-server
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://toledo:123@mongo:27017/TallerMilca?authSource=admin
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=change_this_secret_in_prod
      - PORT=4000
    volumes:
      - ./Express-server:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongodb_taller
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: toledo
      MONGO_INITDB_ROOT_PASSWORD: "123"
      MONGO_INITDB_DATABASE: TallerMilca
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  react:
    build:
      context: ./ReactWithForm
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ReactWithForm:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - express

volumes:
  mongo-data: