services:
  express:
    build:
      context: ./Express-server
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=change_this_secret_in_prod
      - PORT=4000
    volumes:
      - ./Express-server:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres_taller
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  react:
    build:
      context: ./ReactWithForm
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ReactWithForm:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - express
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"

volumes:
  pg-data:
